### ISSUE TITLE
摇杆和指向器的方向不一致

### ISSUE THREAD

**Issue by FourTest** [Bian-Sh/UniJoystick#2]
如图所示,摇杆和指向器的方向不一致
![1](https://github.com/user-attachments/assets/c8957a9c-d812-4cb1-abfb-25f2271daa88)

**Comment by Bian-Sh** [comment]
谢谢提醒，是上个 PR 导致了逻辑异常，还导致了摇杆限定逻辑失效了，我回退了之前的版本

**Comment by Bian-Sh** [comment]
如果大家有这种手指贴合的需求，再讨论吧，我看到很多主流手游摇杆都是我目前这种体验
